### ISSUE TITLE
Particle Speed and Vector options

### ISSUE THREAD

**Issue by Woodyso** [CJCrafter/BiomeManagerWiki#6]
### Description

**Description:**
Allow for the particle speed and travel vector as options in the _/biomemanager particle_ command.

### Configuration

**Configuration:**
/biomemanager particle minecraft:biome minecraft:particle density _speed vectorx,vectory,vectorz_ 

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
Unfortunately, this is not possible. Particles spawned by biomes are pretty different from particles generated by commands/plugins. The most similar thing we can do is add support for `DustColorTransition` particles, but that is not exactly what you want.

Sorry.
